language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - recruitmanage

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email:
    - dev4hkpking@gmail.com
    - ywsaau77@gmail.com
    - joenggyu0@gmail.com
script: ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport coveralls
